### ISSUE TITLE
cbf_deterministic.py doesn't work as expected

### ISSUE THREAD

**Issue by jaztsong** [Berk-Tosun/cbf-cartpole#1]
Hello,

Thanks for putting those examples together. It really helped CBF beginners like me.

A quick question: I wonder why the cbf_determinstic doesn't active ASIF function. It looks like CBF doesn't work at all.

My gut feeling is that the h_t is not a valid CBF as _h_dot is not a function of u at all.

But I could be wrong.

Appreciate any help.

**Comment by Berk-Tosun** [comment]
Hi,

You are correct; cbf_deterministic was not working. I had uploaded an incomplete version.

Now, I have updated it with a working version (513f53626756878e359bbc2975cf96e7b08e1f32). It turned out that it is tricky to get it running :).

Thank you for your kind words.
